### PR TITLE
fix blocking count showing 0 while waiting for request

### LINKED ISSUE #334: Blocking count show 0 while still waiting on request to return.
**Describe the bug**
On the blocking tab:

The list of blocks loads quicker than the count if it is high. While waiting for the count to come back from the server the count displays 0. 

**To Reproduce**
1. Go to https://clearsky.app/palomar.bsky.social/blocking

**Expected behavior**
The count should still show the "loading" status while waiting for the response.

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by IGIRANEZAJosue**
This PR fixes the blocking count showing 0 while still waiting on request to return the number of blocked accounts 

Closes #334

### CODE REVIEW

File: src/detail-panels/blocking/index.jsx [hunk 1]
```diff
@@ -18,8 +18,8 @@ export default function BlockingPanel() {
       totalQuery={totalQuery}
       header={({ count }) => (
         <>
-          {localise(`Blocking ${count.toLocaleString()}`, {
-            uk: `Блокує ${count.toLocaleString()}`,
+          {localise(`Blocking ${!count ? 'loading...' : count.toLocaleString()}`, {
```
Comment (iAmNsengi) [inline src/detail-panels/blocking/index.jsx:21]: So wouldn't this mean whenever the count happens to be zero we display "loading..." ?
I mean, what if the count is actually zero from the response of the server??

**Review by iAmNsengi — CHANGES_REQUESTED** [review]

**Comment by Angekarara** [comment]
LGTM!

**Review by iAmNsengi — APPROVED** [review]
Kudos 👌

**Review by Angekarara — APPROVED** [review]

**Review by noahm — CHANGES_REQUESTED** [review]
This doesn't seem to fix the issue at all when using the same production api as the main site. See: https://clearsky-ui-git-fork-igiranezajosu-552ca3-thieflord06s-projects.vercel.app/palomar.bsky.social/blocking?api=prod

(you can also add the `?api=prod` query to your local server to test against the prod api during development)

**Comment by thieflord06** [comment]
@IGIRANEZAJosue any update on this?

**Comment by IGIRANEZAJosue** [comment]
> @IGIRANEZAJosue any update on this, is this ready?

@thieflord06 Yes, it is ready. 👍🏾

**Review by Angekarara — APPROVED** [review]
Clean loading state handling. LGTM!✅

**Review by iAmNsengi — APPROVED** [review]

**Review by noahm — APPROVED** [review]
This is working better now. Thanks for the fix!
